nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.6.4.cjs

packageExtensions:
  eslint@*:
    peerDependenciesMeta:
      "@typescript-eslint/parser":
        optional: true
      "@typescript-eslint/eslint-plugin":
        optional: true

